# Generated by Django 6.0.5 on 2026-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='guest_user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='AP00XX0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('EV', 'EV')], default='Car', max_length=10),
            preserve_default=False,
        ),
    ]
