# Generated by Django 6.0.5 on 2026-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0002_remove_booking_user_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
